// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2QQubNZ5eP-TlVipV5eSlvDe2rsknl1c',
    appId: '1:10817099231:web:dece8f956dbed06607606a',
    messagingSenderId: '10817099231',
    projectId: 'its-urgent-adb83',
    authDomain: 'its-urgent-adb83.firebaseapp.com',
    storageBucket: 'its-urgent-adb83.appspot.com',
    measurementId: 'G-MHZV0BZCGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJYFiu3micgVtQp9qMflKt1Gtml7KpgM',
    appId: '1:10817099231:android:5b492274dc897aa907606a',
    messagingSenderId: '10817099231',
    projectId: 'its-urgent-adb83',
    storageBucket: 'its-urgent-adb83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zTw2wxISoOmaT8IiKNnxRVRFRBTGpnA',
    appId: '1:10817099231:ios:04b01967c800dc7c07606a',
    messagingSenderId: '10817099231',
    projectId: 'its-urgent-adb83',
    storageBucket: 'its-urgent-adb83.appspot.com',
    iosBundleId: 'com.example.itsUrgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5zTw2wxISoOmaT8IiKNnxRVRFRBTGpnA',
    appId: '1:10817099231:ios:100dd418bac824c807606a',
    messagingSenderId: '10817099231',
    projectId: 'its-urgent-adb83',
    storageBucket: 'its-urgent-adb83.appspot.com',
    iosBundleId: 'com.example.itsUrgent.RunnerTests',
  );
}
